class Locators:
    name_input = "//label[contains(text(), 'Имя')]/following-sibling::input[@name='name']"
    name_value = "//input[@name='name']"
    email_input = "//label[contains(text(), 'Email')]/following-sibling::input[@name='name']"
    password_input = "//label[contains(text(), 'Пароль')]/following-sibling::input[@name='Пароль']"
    signin_button = ".//button[text()='Зарегистрироваться']"
    login_button = ".//a[@href='/login']"
    login_to_account_button = ".//button[text()='Войти в аккаунт']"
    enter_button = ".//button[text()='Войти']"
    logout_button = ".//button[text()='Выход']"
    constructor_button = ".//p[text()='Конструктор']"
    logotype_button = ".//div[@class='AppHeader_header__logo__2D0X2']"
    personal_account_button = ".//p[text()='Личный Кабинет']"
    constructor_bread = ".//span[text()='Булки']"
    selected_bread = "//*[contains(@class, 'tab_tab_type_current') and span[text()='Булки']]"
    constructor_sauce = ".//span[text()='Соусы']"
    selected_sauce = "//*[contains(@class, 'tab_tab_type_current') and span[text()='Соусы']]"
    constructor_topping = ".//span[text()='Начинки']"
    selected_topping = "//*[contains(@class, 'tab_tab_type_current') and span[text()='Начинки']]"